### ISSUE TITLE
 Illegal data address problem

### ISSUE THREAD

**Issue by pietrach** [aldas/modbus-tcp-client#56]
I use Modbus master slave simulator

![obraz](https://user-images.githubusercontent.com/5420924/80406124-d9112080-88c3-11ea-91db-bc1cdfb3b77b.png)

![obraz](https://user-images.githubusercontent.com/5420924/80406173-ededb400-88c3-11ea-8802-4d47d1a15db5.png)

Code receive an error:

```
Packet to be sent (in hex): 8b7f00000006000400d60001
Binary received (in hex): 8b7f00000003008402
ModbusTcpClient\Exception\ModbusException Object ( [message:protected] => Illegal data address [string:Exception:private] => [code:protected] => 2 [file:protected] => D:\wamp\www\modbus\vendor\aldas\modbus-tcp-client\src\Packet\ResponseFactory.php [line:protected] => 85 [trace:Exception:private] => Array ( [0] => Array ( [file] => D:\wamp\www\modbus\test.php [line] => 28 [function] => parseResponseOrThrow [class] => ModbusTcpClient\Packet\ResponseFactory [type] => :: [args] => Array ( [0] => �� ) ) ) [previous:Exception:private] => [xdebug_message] => ( ! ) ModbusTcpClient\Exception\ModbusException: Illegal data address in D:\wamp\www\modbus\vendor\aldas\modbus-tcp-client\src\Packet\ResponseFactory.php on line 85 Call Stack #TimeMemoryFunctionLocation 10.0001401160{main}( )...\test.php:0 20.0392439400ModbusTcpClient\Packet\ResponseFactory::parseResponseOrThrow( )...\test.php:28 ) Illegal data address
#0 D:\wamp\www\modbus\test.php(28): ModbusTcpClient\Packet\ResponseFactory::parseResponseOrThrow('\x8B\x7F\x00\x00\x00\x03\x00\x84\x02') #1 {main}
```

**Comment by aldas** [comment]
@pietrach is that test program set to emulate  'unit id'/'slave id' = 1 scenario?   If so then you need to create packet as
```
$unitId = 1;
$packet = new ReadInputRegistersRequest($startAddress, $quantity, $unitId);
```

**Comment by pietrach** [comment]
@aldas result the same

```
Packet to be sent (in hex): 07b300000006010400d60001
Binary received (in hex): 07b300000003018402
ModbusTcpClient\Exception\ModbusException Object ( [message:protected] => Illegal data address [string:Exception:private] => [code:protected] => 2 [file:protected] => D:\wamp\www\modbus\vendor\aldas\modbus-tcp-client\src\Packet\ResponseFactory.php [line:protected] => 85 [trace:Exception:private] => Array ( [0] => Array ( [file] => D:\wamp\www\modbus\test.php [line] => 28 [function] => parseResponseOrThrow [class] => ModbusTcpClient\Packet\ResponseFactory [type] => :: [args] => Array ( [0] => �� ) ) ) [previous:Exception:private] => [xdebug_message] => ( ! ) ModbusTcpClient\Exception\ModbusException: Illegal data address in D:\wamp\www\modbus\vendor\aldas\modbus-tcp-client\src\Packet\ResponseFactory.php on line 85 Call Stack #TimeMemoryFunctionLocation 10.0002401160{main}( )...\test.php:0 20.0332439400ModbusTcpClient\Packet\ResponseFactory::parseResponseOrThrow( )...\test.php:28 ) Illegal data address
#0 D:\wamp\www\modbus\test.php(28): ModbusTcpClient\Packet\ResponseFactory::parseResponseOrThrow('\x07\xB3\x00\x00\x00\x03\x01\x84\x02') #1 {main}
```

![obraz](https://user-images.githubusercontent.com/5420924/80407278-ad8f3580-88c5-11ea-98bf-fdc79f65c7a5.png)

**Comment by pietrach** [comment]
It's working:

![obraz](https://user-images.githubusercontent.com/5420924/80408166-09a68980-88c7-11ea-82ed-87cd6faef1a7.png)

```
Packet to be sent (in hex): b41600000006010400d50001
Binary received (in hex): b41600000005010402003a
Parsed packet (in hex): b41600000005010402003a
Data parsed from packet (bytes):
Array ( [0] => 0 [1] => 58 ) Array ( [0] => 0 [1] => 58 ) Array ( [0] => 0 [1] => 58 ) 
```

**Comment by aldas** [comment]
very good. I think it has to do how modbus slave program addressing is set

see:
![modbus-unit](https://user-images.githubusercontent.com/2320301/80408617-24313080-88d0-11ea-85c2-8fcb07515a99.png)

**Comment by pietrach** [comment]
But I don't understand:

![obraz](https://user-images.githubusercontent.com/5420924/80409256-d1a04600-88c8-11ea-9dd7-6deca503801b.png)

Result is:
```

Packet to be sent (in hex): f35100000006010400d50001
Binary received (in hex): f351000000050104021104
Parsed packet (in hex): f351000000050104021104
Data parsed from packet (bytes):
Array ( [0] => 17 [1] => 4 )
Array ( [0] => 17 [1] => 4 )
Array ( [0] => 17 [1] => 4 ) 
```

Why ?

**Comment by pietrach** [comment]
Ok, It's working

```
 $responseWithStartAddress = $response->withStartAddress($startAddress);
 print_r($responseWithStartAddress->getWordAt($startAddress)->getInt16());
```

return 4356

**Comment by aldas** [comment]
Nice. You got everything working @pietrach? Can I close this ticket?

**Comment by pietrach** [comment]
I think so but it isn't known what else will happen during :-)
